backend:
  name: git-gateway
  branch: main

media_folder: "img"
public_folder: "/img"

collections:
  - name: "setup"
    label: "Ürün Yönetimi"
    delete: false
    files:
      - name: "all_products"
        label: "Tüm Ürünler"
        file: "data/product.json" # Veri buraya yazılacak
        fields:
          - label: "Ürünler"
            name: "products"
            widget: "list"
            fields:
              - { label: "Ürün Adı", name: "name", widget: "string" }
              - { label: "Açıklama", name: "description", widget: "text" }
              - label: "Kategori"
                name: "category"
                widget: "select"
                options: ["Plastik Çakmak", "Promosyon Çakmak", "Metal Çakmak", "Diğer Modeller"]
              - { label: "Ürün Görseli", name: "image", widget: "image" }
              # config.yml içinde fields altına ekleyin
              - { label: "Ürün Görseli (Dosya)", name: "image", widget: "image", required: false }
              - { label: "Ürün Görseli (URL)", name: "image_url", widget: "string", required: false }
              - { label: "Popüler mi?", name: "popular", widget: "boolean", default: false }