backend:
  name: git-gateway
  branch: main

media_folder: "img"
public_folder: "/img"

collections:
  - name: "settings"
    label: "Ürün Yönetimi"
    delete: false # Dosyayı silmeyi engelle
    editor:
      preview: false
    files:
      - name: "all_products"
        label: "Tüm Ürünler"
        file: "data/product.json" # Tüm ürünler tek dosyada duracak
        fields:
          - label: "Ürün Listesi"
            name: "products"
            widget: "list"
            fields:
              - { label: "Ürün Adı", name: "name", widget: "string" }
              - { label: "Açıklama", name: "description", widget: "text" }
              - label: "Kategori"
                name: "category"
                widget: "select"
                options:
                  - "Plastik Çakmak"
                  - "Promosyon Çakmak"
                  - "Metal Çakmak"
                  - "Diğer Modeller"
              - { label: "Ürün Görseli (1080x1350)", name: "image", widget: "image" }
              - { label: "Popüler mi?", name: "popular", widget: "boolean", default: false }